### ISSUE TITLE
Add Tangler game to "Made with KTX" site section

### ISSUE THREAD

**Issue by andrzej-nov** [libktx/libktx.github.io#16]
Hello! If you'd like, please add my game https://github.com/andrzej-nov/Tangler#tangler to the ["Made with KTX" site section](https://libktx.github.io/#showcase-section). It is a 2D casual logic puzzle game, complete at the moment (except for a few possible bugfixes).

Thank you for KTX :)

**Comment by czyzby** [comment]
Looks pretty sweet! No promises on when, but I'll try to update the website with the missing KTX modules and some more game examples. Thanks for the submission.

**Comment by czyzby** [comment]
By the way @andrzej-nov, feel free to share it in [KTX discussions](https://github.com/libktx/ktx/discussions). The website works mostly as an introduction page for the new users, but I suspect there might be more traffic from the existing KTX developers in the main repo.

**Comment by andrzej-nov** [comment]
Thank you! I will do.

**Comment by czyzby** [comment]
@andrzej-nov I'll add it to the website, I'm just waiting on some icons so I can update it in one batch.

**Comment by czyzby** [comment]
@andrzej-nov I've added your game to the showcase, along with the new icons for `ktx-reflect` and `ktx-script` modules from @marszaa. Thanks again for linking your game and using KTX!

@Quillraven I've also added [Dinoleon](https://github.com/Quillraven/Dinoleon) to the website. I think an example of a project using ECS might be pretty useful. Cheers.
