### ISSUE TITLE
add app "Connections" to the "Made with KTX" section on the website

### ISSUE THREAD

**Issue by swantescholz** [libktx/libktx.github.io#6]
Hello, I programmed a little free Android app using libKTX: https://github.com/swantescholz/connections-app
If you like, feel free to add it to the "Made with KTX" section of the website.
Let me know if you have any questions.
Regards,
Swante

P.S.: Thanks for developing libKTX. I really loved programming with it!

**Comment by czyzby** [comment]
Hey @swantescholz, I missed the notification for this issue. Thank you for using KTX and this contribution! Your game is a practical example of what can be developed with KTX that could be useful for beginners starting with the framework, but I'd rather add applications with a little bit more polished graphics to the showcase. You can go ahead and post info about your project in [the examples issue](https://github.com/libktx/ktx/issues/19) in the original repo.
